on:
  push:
    branches:
      - test-deployment

jobs:
    deployment:
        name: Deployment
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout"
              uses: actions/checkout@master
            - uses: actions/setup-node@v1
              with:
                  node-version: "8.16.0"
                  registry-url: https://npm.pkg.github.com/
            - name: "Install dependencies"
              run: npm i --verbose
            - name: "Deploy to the internal server"
              uses: burnett01/rsync-deployments@4.0
              with:
                switches: -avzr --delete
                path: client/
                remote_path: /var/workspace/vmr/vmr-test
                remote_host: root
                remote_user: 161.35.217.162
                remote_key: -----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAxs2C37JB7phFWlN2Nn67bMwh6RAcIXy9CwCi25MNLyjOmkmQ
g4gXCBS67qB0tJ5DJY55BjC0MqedRwJ5JEI1C85ZDsdCU/m5PVWhJryYlVdY7ClU
IDYflW/0TOFPwmvWIFyZuSSSNESR0pqJQjTc05Kov8nDnJnaJJDFhtmKKnphnnHr
QlMFs1NiO7PUpOfpWldRGtfj3zOSStreSD3rHIz/mhbJ/1BiGb7jDDG8dj9qGYeb
lFgmvgSq0WcI0svBKMwm7juxtWtmwvqxjngoiRxkiFY43iypNi+tjSvm5jsSstPK
wcZUO/LiglKINLH67v/2AamypfJ93mcEWtKQTQIDAQABAoIBAQCxL7vkenEvIYI2
lkq3GU8dEfdrTRN1eULYSpHcV/0ZOiqh8s0dni7A4hEV2+cIkEHSeGA/dys0NpYE
Ex07htLWmexgMpJYXCuQkgBWkSMBf99eZRt4tiSCQU0hNHOtGgW3xDCyhfjVIwRB
C8EoRAtJet5ySXbR3YJCstGKddsiLW0tRyhZVrILRlrTggiBe4rQ/lngMB5YhPiw
sTBpZ2Xa5GlkO6TVEZCJzgjYl7Iz1g0/A7Nt8DmBxDY5oJnQb5uaCRHx4CCHr5a5
r6nKLANQUDIBX5G9ylhfNJukUqEgc1Z8e7gz6IleTzcvkEAh4t2vI/suxproZ2bw
YPYgCV1hAoGBAOK6Yb/SurW/4jvWjsJ6h2Z0dM4CGCZnPfbfEKWVVBdoGTVqenYO
FOgOK/LYPL6lr2VtCDWEz5MPND3yEq/678OSxfKoyNt5LNRmE6URosb9tFOFYaQq
GXGmldTGWkvXMlmqvr2qLFOq4TW7sXGoi5zOb1Z4fCLcE67ZMIP/TAxJAoGBAOB4
KuE0Dih0MAAK2RDD4vHSm9qsrfPfgkiDqcjOFlHCh0quO2zhn6i3IRknCegipm1E
fJ46HiCFqndowD1DMfCzzU6+RYNhafRizwrd4rzLy6HOTrT7Drca260YHgnktTx/
NV7to1Tz2nWCtCVCfB9HW6XLo4LhoLeJ4zSNwPvlAoGAZ0qkN8DoYN7fUYWJGl66
CtopUKUxnWVRnIO5UMZ8PgGl4mj1C42UxreWHBeZbP2Mr7eBkuhDrOqzUTlUfCnl
S4M1fTyZ7SsCWm16q6wiLWft3FMazbCEUPukrQAEqSKMBL++EChT83YZDeLJj09K
85A0tv9DBpqeuPynlqsbWUkCgYEA1CAbfZkA7C/okJGv0g0b8aUzDfLzrKyC5V4v
XAmNxBQOYH/Ivrt1cy4khC2FSi88kbQQBEMt51QJ5TBDw2E1159DHO/opyCuzXl2
6XEIbZw1wqJBdPxwSo+CG9DXyketEg+w8xWlrYmI4FX1QeTTgYegz0xjKDNq+ye+
ZBK11hUCgYA9kUyylKtI2EemFkI8chtNKuZAnnUYaUbKfxSUdwQBBFrJUJTcasFb
xHX1/vnqDyBS8Yp2GbdPn9yMhIjf8nR4YTyGK4tLp/PqrgMcO3OCV3mHoxgPf48T
/Wpcgbtfl+o3lkZ0XwEuasKKpnJ3P4uD89yZ2TNYNVQ640KXBcfVlw==
-----END RSA PRIVATE KEY-----