on:
  push:
    branches:
      - master

jobs:
    deployment:
        name: Deployment
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout"
              uses: actions/checkout@master
            - uses: actions/setup-node@v1
              with:
                  node-version: "12.16.3"
                  registry-url: https://npm.pkg.github.com/
            - name: "Install dependencies"
              run: npm i --verbose
            - name: "Install frontend deps and build"
              run: "cd client/ && npm install && npm run build"
            - name: "Deploy to the internal server"
              uses: burnett01/rsync-deployments@4.0
              with:
                switches: -avzr
                path: /
                remote_path: /var/workspace/vmr/prod/
                remote_host: 161.35.217.162
                remote_user: root
                remote_key: ${{ secrets.SSH_PRIVATE_KEY }}